### ISSUE TITLE
Typo: Copy/Past/Edit on https://masscode.io/snippets/

### ISSUE THREAD

**Issue by pranavarora1895** [massCodeIO/snippet-collection#8]
![massCodeIssue](https://user-images.githubusercontent.com/48170643/180635068-1ba1c0f6-f3f7-4265-b2b8-150ef6f34ecc.JPG)

_Kindly Fix the typo from **Copy/Past/Edit to Copy/Paste/Edit**._

**Comment by antonreshetov** [comment]
Oh...I look, but I don't see ))

**Comment by antonreshetov** [comment]
Closed because it was fixed [492b7de](https://github.com/massCodeIO/snippet-collection/commit/492b7de478cada8392ace4fa4a7e8b2f663e81e0)
